### ISSUE TITLE
Kickoff Meeting

### ISSUE THREAD

**Issue by hexylena** [galaxy-carpentries/organisation#1]
Our Kickoff Meeting is October 26th, 15-17 CET

Minutes document: https://docs.google.com/document/d/1k8daES74rpeFK9roQDGWxotEPHURto-fYZBJlpIFZ8k/edit?usp=sharing

# Agenda

- Welcome
- Scope of the grant
	- Review Intellectual Outputs
	- Teams
		- Anyone you're working with or will be helping?
	- Deliverables / What we're evaluated on
- First 6 months
	- Discuss our detailed plans we came up with
	- Course in February as first event for IO1/2
	- Does that format work for us?
	- Second one for IO3/4 to plan
- Communications
	- Github
	- Meeting Schedule
	- Time everyone can meet for partner-wide monthly telco.
	- Paperwork
		- Timesheets
		- Final grant agreement (@shiltemann will put in GDrive for your records)

**Comment by hexylena** [comment]
# Agenda & Minutes

(Please feel free to add any points you would like to discuss today in the list below)
-   Welcome & Introductions
-   Communication Channels
    -   Can everybody access all the links above?
    -   Teams
        -   Anyone you're working with or will be helping?
            -   Anthony: 1
            -   Bérénice: Bea, Cristobal (November)
            -   Yvan: Coline
        -   Anybody who should be added to Gitter/GitHub/other? Let us know!
    -   Meeting Schedule
        -   Suggestion: monthly partner-wide telcos.
            -   When? This time ok structurally? **Yes! It seems to be**
            -   First Monday of the month, 15:00-16:00 CET (starting > December 7)?
-   **Report of Erasmus+ Kickoff Meeting** (06-10-2020) [Saskia & Helena]
    -   [*Slides*](https://drive.google.com/drive/folders/1pKni0scyVelRyBtO0Cw8j60YG_Tv6hRn) (mostly in Dutch)
    -   [*Mobility Tool*](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=199161281) (Project Management/Reporting tools from EC for coordinators, partners can view)
    -   Focus on impact
        -   Impact was 30/100 points on proposal, 40/100 on final assessment
        -   They seem very open to changes in plan if motivated by impact
        -   [*Impact tool*](https://www.erasmusplus.nl/impacttool-strategischepartnerschappen) to help define/articulate/assess impact, to help guide the project
    -   We must have EU logo visible on any activities related to Gallantries
        -   Added image to Gdrive
        -   Added to Gallantries website \[Helena\]
        -   Add to GTN logo list \[Saskia\]
    -   Given pandemic, digital signatures are fine for now (e.g. for timesheets), they might ask for "wet" signatures down the road.
    -   Monitoring by EC
        -   Risk-based (based on our reporting) and random spot checks
        -   EC may decide to attend our project meetings and events (Annex III)
        -   Yearly + Midterm + End reports
            -   *Sept 1st start date*
            -   they can reduce the money they give based on the final score.
            -   never happened before in NL
        -   Control of our paperwork up to 5 years after project.
    -   "Association link"
        -   All y'all are formal employees of your institutions right?
        -   *EMC receives, then disburses to Institutes, then they can            subdivide*
    -   Any changes in how we're spending, must be passed on
        -   Up to 20% may be transferred between budget posts without             formal amendment.
-   **First Six Months - Project-wide activities**
    -   Events
        -   Course in February (15-19) as first event for IO1/2
            -   Goal: Assess whether this format works for us in lieu of  hybrid training format.
        -   Second one for IO3/4 to be planned
    -   Develop feedback/impact assessment surveys
        -   Align with ELIXIR, others?
    -   Dissemination Channels
        -   Create a mailing list for our stakeholders?
        -   Social Media? Twitter! \[Fotis\]
        -   Update Gallantries website \[Helena working on it\]
    -   Anything else?
-   **First Six Months - Detailed IO Plans!**
    -   **IO1 - \[CERTH, EMC\]** Introduction to data analysis and management, statistics, and coding
        -   *(Stretch)* Intro to Programming Concept
            -   What are functions
            -   What are variables
            -   Slower w/ more exercises, some ROSALIND type exercises?
        -   Coding in R
            -   a lot is done with R code. GTN modules are OK.
            -   do we need to update these? (I know of 1 broken link)
            -   we did the demo ggplot2, maybe include that?
            -   Update w/ new tidyverse
            -   Make it a bit bigger? more exercises, starting from scratch maybe?
        -   Coding in Python3
            -   Consider RStudio w/ Python? (shows variables/datastructures/etc)
                -   pedagogically better to unify on one platform, not switch?
            -   *FP: If you want to increase impact, maybe use jupyter*
            -   Avoid viz in python? Discuss later.
            -   *BB: anne was working on jupyter? Can we coordinate?*
            -   [*https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/jupyterlab/tutorial.html*](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/jupyterlab/tutorial.html)
            -   [*https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/galaxy-intro-jupyter/tutorial.html*](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/galaxy-intro-jupyter/tutorial.html)
            -   *FP: Reuse the R for python? Advanced replicating the  advanced R maybe.*
        -   Intro to Command line
            -   New interactive tool for an Ubuntu Desktop (Or Rstudio! That's easy)
            -   Bash
            -   Practical tools
                -   Github/git?
                -   *(Stretch)* Make a PR?
            -   *Stretch goal*: Scientific Collaboration (how to review  code/PR, work together.)
        -   *AS: use case focused development maybe? Something getting
            increasingly more complex with similar datasets or analyses
            as a thread/link between them?*
    -   **IO2 - \[EMC/ALU-FR\]** Large-scale data analysis, and introduction to visualization and data modelling
        -   Intro to Scaling
            -   collections: update the tutorials / tips n tricks  (\@shiltemann?)
            -   how to work on workflows (editor, subworkflows, collections, test expression tools & tuto if working.) (\@hexylena)
            -   Rule based, nametags, group tags (\@hexylena)
            -   Tutorials need to be more real world (\@shiltemann)
            -   Workflow Reports (\@hexylena)
        -   Intro to human microbiome
            -   Expand intro slides
            -   16s with Mothur (\@shiltemann)
                -   *stretch*: 16s w/ QIIME 2? (\@shiltemann)
        -   Advanced Microbiome analysis
            -   Shotgun metagenomics (\@bebatut)
                -   Add more visualizations
            -   Metatranscriptomics one to metagenomics? (\@bebatut)
                -   Work with GalaxyP there?
            -   Oleg (Freiburg) is working to make automatic gifs of the snippets?
            -   Miaomiao WF (\@shiltemann)
            -   Nanopore ABR tutorial (\@shiltemann, willem, astrid)
                -   Update nanopore to WF helena made?  (\@hexylena/astrid)
        -   Other
            -   Considering metagenomics related content, We (MNHN) are thinking creating a Interactive Tool based on Ranacapa R shiny app [*https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6305237/*](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6305237/)  dedicated to eDNA data analysis
            -   Virus?
    -   **IO3 - \[INRAE/EMC\]** Data stewardship, federation,  standardisation, and collaboration
        -   Intro to Genomics and GA
            -   lots of content needed
            -   Data management (histories, naming, tagging, data  storage, etc.?) (\@hexylena)
            -   Data sources (genomics?)
            -   Adapt [*GA introduction  slides*](https://training.galaxyproject.org/training-material/topics/genome-annotation/slides/introduction.html) (remove euk slides)
            -   FAIR (andrew)
        -   Intro to Proks / biology
            -   Collaborative Curation (everyone on one test  org \@hexylena)
            -   Apollo working on EU and everything flowing enough to  work for events. (\@hexylena)
            -   Apollo : check permissions + name collisions
            -   Review Prokka tutorial, + add more functional annot ?
            -   Finish [*pending apollo pull request*](https://github.com/galaxyproject/training-material/pull/1484)
            -   Some Python coding to compute stats on annotated genes ?
            -   (Started work on a shortened Maker tuto for later too)
        -   Discussion
            -   FP: Maybe overlap with IO1 for their Python3 module?
            -   Crossmap?
            -   Yvan: maybe a link to do between IO3 and \"ELIXIR  Community-led Implementation Study 2020 PROPOSAL Strengthen Data Management in Galaxy\" querying  metadata contents of an exported history file [https://github.com/usegalaxy-no/nels-galaxy-api](https://github.com/usegalaxy-no/nels-galaxy-api)
            -   Yvan: Research Objects / Discussions on that with Nicola/Hadley
            -   Andrew: link it back to elixir projects like aai?
            -   [*https://github.com/inab/EPICO-data-model/blob/fairtracks/model-docs/general-schema.pdf*](https://github.com/inab/EPICO-data-model/blob/fairtracks/model-docs/general-schema.pdf)
            -   *https://github.com/fairtracks/fairtracks\_standard*
    -   **IO4 - \[MNHN/ALU-FR\]** Data analysis and modelling for  evidence and hypothesis generation and knowledge discovery
        -   Biodiversity data handling and visualisation
            -   Raw data to analyses through modelling approach (GLM)
            -   WF is complete already !
            -   Rstudio flavour?
    -   **IO5 - \[ALU-FR/CERTH\]** TtT & Mentor Programme
        -   Most of the work will start after February when Bérénice is
            back full time
            -   What can we do to help with this before then?
        -   Discuss with the freiburg folks (Bea/Christobal)
        -   Train-the-Trainer program
        -   Feedback form for the trainers
            -   Discuss the contents of this form
            -   Disseminate to the trainers/helpers during event
        -   Course builder
            -   Provide some example schedules based on our own  experiences?
            -   Tool to let you build your own (using metadata on prerequisite and follow-up tutorials, expected length, etc)
            -   (Maybe a masters project? VueJS, machine learning 😭)
            -   Maybe TeSS is an option to integrate with, we'll have to  keep in touch with them.
-   **Communications**
    -   GitHub
        -   Bérénice: is reading her emails (gh issues on monday)
        -   Yvan: email.
    -   Meeting Schedule
        -   Suggestion: monthly partner-wide telcos. When? This time?  First Monday of the month, 15:00-16:00 CET (starting December 7)?
    -   Paperwork
        -   Timesheets (per person, per IO)
            -   [*Template*](https://drive.google.com/file/d/1ohhSzmcSCaO-jQUbkKLW29rAb0_Ktz_o/view?usp=sharing) in reports folder of Gdrive
            -   We'll place ours in gdrive
        -   Final grant agreement  ([*\@shiltemann*](https://github.com/shiltemann) will put in GDrive for your records)
    -   Quizzing students
        -   [*https://kahoot.it*](https://kahoot.it) was used in kickoff meeting with EC, which was quite nice. We could consider doing similar things in our events (you just joined with a phone/browser, it was relatively privacy preserving, and we can use it to gauge knowledge maybe??)
    -   **Please record all our dissemination activities** in [*this document*](https://docs.google.com/document/d/17qN3PS5rPoqGszwr-PWIQPwgBG1dLx8PI2B2dciVBro/edit) in Gdrive  any blog posts, emails to mailing lists, presentations, etc\
-   **AOB?**
    -   Any other business anybody would like to raise?\
-   Next Meeting: TBA

# Action Items

**Action**  |                                                         **Who**
---- | ----
Update Gallantries website                                           |Helena
Add EU logo to GTN website                                           |Saskia
Go through impact tool in next meeting, what impacts we expect/how   |H
Rename org                                                           |H
Blog post                                                            |H
Coordinate with CINECA on impact/feebdack                            |Saskia
Coordinate with Elixir                                               |H
Twtitter Account Create + share with us?                             |Fotis
Can freiburg use HiWis?                                              |Saskia / EMC
Fotis will invite us to the TeSS club                                |Fotis
FAIR workshop                                                        |Andrew
Timesheet/paperwork                                                  |Saskia / EMC

**Comment by saskia** [comment]
wrong email address

**Comment by saskia** [comment]
wrong email address. stop mailing me.

**Comment by hexylena** [comment]
Sorry about the inadvertent pings! I copied and pasted this from another document.
