### ISSUE TITLE
[2021] Prokaryotic annotation

### ISSUE THREAD

**Issue by hexylena** [galaxy-carpentries/organisation#23]
- [ ] Lesson Development & Review
- [ ] Pilot Workshop
- [ ] Lesson Development & Review
- [ ] Scale Up
- [ ] Analyse feedback

@hexylena copy from tamu?

**Comment by hexylena** [comment]
Delaying this to year 2, the planned tutorials require tools not yet published but will be soon.

**Comment by abretaud** [comment]
Do you have specific tools/tutos in mind?
For prokaryotic genomes we have the prokka tutorial, and the apollo tutorial is based on E. coli too
(I don't remember if we already discussed this in details!)

**Comment by hexylena** [comment]
I've forgotten if we've discussed in detail at all! Ahh the e. coli counts, never mind then :D 

I was thinking of the phage workflows/tutorials, but, ok, those can 'count' retroactively when they're there, and we check this off for now.

**Comment by hexylena** [comment]
Tutorials produced for this objective:

- https://training.galaxyproject.org/training-material/topics/genome-annotation/tutorials/apollo/tutorial.html
- https://training.galaxyproject.org/training-material/topics/genome-annotation/tutorials/apollo/slides.html

**Comment by abretaud** [comment]
Good, on issue closed :)
But yes, phage stuff would be great! Let me know if/when I can help on that!
