### ISSUE TITLE
[2022] FAIR Data

### ISSUE THREAD

**Issue by hexylena** [galaxy-carpentries/organisation#24]
- [ ] Lesson Development & Review
- [ ] Pilot Workshop
- [ ] Lesson Development & Review
- [ ] Scale Up
- [ ] Analyse feedback

@bebatut just submitted a proposal for fairification of workflow. One part is "document everything", maybe can create training IF they have funding on that. **Update** they got funding! End of Year.

@shiltemann will check with CINECA

Maybe we can make more of a "checklist" and practical hands-on FAIR training.

"putting WFs in dockstore/WF hub" (xref IWC?)

**Comment by hexylena** [comment]
@abretaud  I think we can use or link to a lot of the RDMkit resources to help us cover the 'data stewardship' bits and pull in content we'll use as discussion points? E.g. the bits like this I think are a good thing to use in our fed/stewardship discussions:

> Accurate documentation of the plant biological materials and samples is critical for interoperability, and should comply with the MIAPPE standard. This information should be submitted to BioSamples, with MIAPPE compliance validated using BioSamples’ plant-miappe.json template

https://rdmkit.elixir-europe.org/plant_genomics_assembly.html#for-what-purpose-can-you-use-the-plant-genomics-tool-assembly

**Comment by abretaud** [comment]
:+1: Yep I totally agree we should base our material on this!

**Comment by hexylena** [comment]
IWC is planning to have a training.

**Comment by hexylena** [comment]
https://training.galaxyproject.org/training-material/topics/fair/
