### ISSUE TITLE
[2022] Metabarcoding and environmental DNA data analysis

### ISSUE THREAD

**Issue by hexylena** [galaxy-carpentries/organisation#29]
- [x] Lesson Development & Review
- [x] Pilot Workshop
- [x] Lesson Development & Review
- [x] Scale Up
- [x] Analyse feedback

**Comment by hexylena** [comment]
@yvanlebras since you missed the meeting can you write a bit about what you plan to do for this here?

**Comment by yvanlebras** [comment]
Hello Helena,
sorry for this morning, hope now with the good e-mail adress this will be better to come to meetings!
The plan here is to test existing tools and training material there https://training.galaxyproject.org/training-material/topics/metagenomics/ and reuse it to propose an "ecology" dedicated tuto and/or amelioration of existing tuto. This seems ok on your side ?

**Comment by hexylena** [comment]
Danke!

**Comment by hexylena** [comment]
xref https://github.com/gallantries/video-library/issues/37

**Comment by hexylena** [comment]
Done in Tapas 2022
