### ISSUE TITLE
Materials to consider / import:

### ISSUE THREAD

**Issue by hexylena** [galaxy-carpentries/organisation#42]
IO1: 

- [ ] https://wilkelab.org/SDS375/schedule.html
- [ ] https://github.com/fpsom/2020-07-machine-learning-sib @fpsom
- [ ] https://github.com/fpsom/elixir-ml-biostats-hackathon
- [ ] http://genomicsclass.github.io/book/
- [ ] https://bio331.devbioinformatics.org/

IO2/3

- [ ] https://genviz.org/course/

**Comment by fpsom** [comment]
I would also propose this https://github.com/fpsom/elixir-ml-biostats-hackathon (the ELIXIR ML lesson, but with Python). This might be a good follow-up if we add a python lesson too.

**Comment by hexylena** [comment]
In the end we did not do these, and instead used other materials.
